// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package contoso.widgetmanager.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.azure.json.JsonReader;
import com.azure.json.JsonSerializable;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;

/**
 * A widget.
 */
@Immutable
public final class Widget implements JsonSerializable<Widget> {
    /*
     * The widget name.
     */
    @Generated
    private String name;

    /*
     * The ID of the widget's manufacturer.
     */
    @Generated
    private final String manufacturerId;

    /*
     * The entity tag for this resource.
     */
    @Generated
    private String etag;

    /**
     * Creates an instance of Widget class.
     * 
     * @param manufacturerId the manufacturerId value to set.
     */
    @Generated
    public Widget(String manufacturerId) {
        this.manufacturerId = manufacturerId;
    }

    /**
     * Get the name property: The widget name.
     * 
     * @return the name value.
     */
    @Generated
    public String getName() {
        return this.name;
    }

    /**
     * Get the manufacturerId property: The ID of the widget's manufacturer.
     * 
     * @return the manufacturerId value.
     */
    @Generated
    public String getManufacturerId() {
        return this.manufacturerId;
    }

    /**
     * Get the etag property: The entity tag for this resource.
     * 
     * @return the etag value.
     */
    @Generated
    public String getEtag() {
        return this.etag;
    }

    /**
     * {@inheritDoc}
     */
    @Generated
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeStringField("manufacturerId", this.manufacturerId);
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of Widget from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of Widget if the JsonReader was pointing to an instance of it, or null if it was pointing to
     * JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the Widget.
     */
    @Generated
    public static Widget fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            String name = null;
            String manufacturerId = null;
            String etag = null;
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("name".equals(fieldName)) {
                    name = reader.getString();
                } else if ("manufacturerId".equals(fieldName)) {
                    manufacturerId = reader.getString();
                } else if ("etag".equals(fieldName)) {
                    etag = reader.getString();
                } else {
                    reader.skipChildren();
                }
            }
            Widget deserializedWidget = new Widget(manufacturerId);
            deserializedWidget.name = name;
            deserializedWidget.etag = etag;

            return deserializedWidget;
        });
    }
}
