// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package contoso.widgetmanager.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.azure.core.util.CoreUtils;
import com.azure.json.JsonReader;
import com.azure.json.JsonSerializable;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.time.format.DateTimeFormatter;

/**
 * A submitted repair request for a widget.
 */
@Immutable
public final class WidgetRepairRequest implements JsonSerializable<WidgetRepairRequest> {
    /*
     * The date and time when the repair is scheduled to occur.
     */
    @Generated
    private final OffsetDateTime scheduledDateTime;

    /*
     * The date and time when the request was created.
     */
    @Generated
    private final OffsetDateTime createdDateTime;

    /*
     * The date and time when the request was updated.
     */
    @Generated
    private final OffsetDateTime updatedDateTime;

    /*
     * The date and time when the request was completed.
     */
    @Generated
    private final OffsetDateTime completedDateTime;

    /**
     * Creates an instance of WidgetRepairRequest class.
     * 
     * @param scheduledDateTime the scheduledDateTime value to set.
     * @param createdDateTime the createdDateTime value to set.
     * @param updatedDateTime the updatedDateTime value to set.
     * @param completedDateTime the completedDateTime value to set.
     */
    @Generated
    public WidgetRepairRequest(OffsetDateTime scheduledDateTime, OffsetDateTime createdDateTime,
        OffsetDateTime updatedDateTime, OffsetDateTime completedDateTime) {
        this.scheduledDateTime = scheduledDateTime;
        this.createdDateTime = createdDateTime;
        this.updatedDateTime = updatedDateTime;
        this.completedDateTime = completedDateTime;
    }

    /**
     * Get the scheduledDateTime property: The date and time when the repair is scheduled to occur.
     * 
     * @return the scheduledDateTime value.
     */
    @Generated
    public OffsetDateTime getScheduledDateTime() {
        return this.scheduledDateTime;
    }

    /**
     * Get the createdDateTime property: The date and time when the request was created.
     * 
     * @return the createdDateTime value.
     */
    @Generated
    public OffsetDateTime getCreatedDateTime() {
        return this.createdDateTime;
    }

    /**
     * Get the updatedDateTime property: The date and time when the request was updated.
     * 
     * @return the updatedDateTime value.
     */
    @Generated
    public OffsetDateTime getUpdatedDateTime() {
        return this.updatedDateTime;
    }

    /**
     * Get the completedDateTime property: The date and time when the request was completed.
     * 
     * @return the completedDateTime value.
     */
    @Generated
    public OffsetDateTime getCompletedDateTime() {
        return this.completedDateTime;
    }

    /**
     * {@inheritDoc}
     */
    @Generated
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeStringField("scheduledDateTime",
            this.scheduledDateTime == null
                ? null
                : DateTimeFormatter.ISO_OFFSET_DATE_TIME.format(this.scheduledDateTime));
        jsonWriter.writeStringField("createdDateTime",
            this.createdDateTime == null ? null : DateTimeFormatter.ISO_OFFSET_DATE_TIME.format(this.createdDateTime));
        jsonWriter.writeStringField("updatedDateTime",
            this.updatedDateTime == null ? null : DateTimeFormatter.ISO_OFFSET_DATE_TIME.format(this.updatedDateTime));
        jsonWriter.writeStringField("completedDateTime",
            this.completedDateTime == null
                ? null
                : DateTimeFormatter.ISO_OFFSET_DATE_TIME.format(this.completedDateTime));
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of WidgetRepairRequest from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of WidgetRepairRequest if the JsonReader was pointing to an instance of it, or null if it was
     * pointing to JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the WidgetRepairRequest.
     */
    @Generated
    public static WidgetRepairRequest fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            OffsetDateTime scheduledDateTime = null;
            OffsetDateTime createdDateTime = null;
            OffsetDateTime updatedDateTime = null;
            OffsetDateTime completedDateTime = null;
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("scheduledDateTime".equals(fieldName)) {
                    scheduledDateTime = reader
                        .getNullable(nonNullReader -> CoreUtils.parseBestOffsetDateTime(nonNullReader.getString()));
                } else if ("createdDateTime".equals(fieldName)) {
                    createdDateTime = reader
                        .getNullable(nonNullReader -> CoreUtils.parseBestOffsetDateTime(nonNullReader.getString()));
                } else if ("updatedDateTime".equals(fieldName)) {
                    updatedDateTime = reader
                        .getNullable(nonNullReader -> CoreUtils.parseBestOffsetDateTime(nonNullReader.getString()));
                } else if ("completedDateTime".equals(fieldName)) {
                    completedDateTime = reader
                        .getNullable(nonNullReader -> CoreUtils.parseBestOffsetDateTime(nonNullReader.getString()));
                } else {
                    reader.skipChildren();
                }
            }
            return new WidgetRepairRequest(scheduledDateTime, createdDateTime, updatedDateTime, completedDateTime);
        });
    }
}
