// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package contoso.widgetmanager.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A widget.
 */
@Immutable
public final class Widget {
    /*
     * The widget name.
     */
    @Generated
    @JsonProperty(value = "name", access = JsonProperty.Access.WRITE_ONLY)
    private String name;

    /*
     * The ID of the widget's manufacturer.
     */
    @Generated
    @JsonProperty(value = "manufacturerId")
    private final String manufacturerId;

    /*
     * The entity tag for this resource.
     */
    @Generated
    @JsonProperty(value = "etag", access = JsonProperty.Access.WRITE_ONLY)
    private String etag;

    /**
     * Creates an instance of Widget class.
     * 
     * @param manufacturerId the manufacturerId value to set.
     */
    @Generated
    @JsonCreator
    public Widget(@JsonProperty(value = "manufacturerId") String manufacturerId) {
        this.manufacturerId = manufacturerId;
    }

    /**
     * Get the name property: The widget name.
     * 
     * @return the name value.
     */
    @Generated
    public String getName() {
        return this.name;
    }

    /**
     * Get the manufacturerId property: The ID of the widget's manufacturer.
     * 
     * @return the manufacturerId value.
     */
    @Generated
    public String getManufacturerId() {
        return this.manufacturerId;
    }

    /**
     * Get the etag property: The entity tag for this resource.
     * 
     * @return the etag value.
     */
    @Generated
    public String getEtag() {
        return this.etag;
    }
}
