// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package contoso.widgetmanager.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.OffsetDateTime;

/**
 * A submitted repair request for a widget.
 */
@Immutable
public final class WidgetRepairRequest {
    /*
     * The date and time when the repair is scheduled to occur.
     */
    @Generated
    @JsonProperty(value = "scheduledDateTime")
    private final OffsetDateTime scheduledDateTime;

    /*
     * The date and time when the request was created.
     */
    @Generated
    @JsonProperty(value = "createdDateTime")
    private final OffsetDateTime createdDateTime;

    /*
     * The date and time when the request was updated.
     */
    @Generated
    @JsonProperty(value = "updatedDateTime")
    private final OffsetDateTime updatedDateTime;

    /*
     * The date and time when the request was completed.
     */
    @Generated
    @JsonProperty(value = "completedDateTime")
    private final OffsetDateTime completedDateTime;

    /**
     * Creates an instance of WidgetRepairRequest class.
     * 
     * @param scheduledDateTime the scheduledDateTime value to set.
     * @param createdDateTime the createdDateTime value to set.
     * @param updatedDateTime the updatedDateTime value to set.
     * @param completedDateTime the completedDateTime value to set.
     */
    @Generated
    @JsonCreator
    public WidgetRepairRequest(@JsonProperty(value = "scheduledDateTime") OffsetDateTime scheduledDateTime,
        @JsonProperty(value = "createdDateTime") OffsetDateTime createdDateTime,
        @JsonProperty(value = "updatedDateTime") OffsetDateTime updatedDateTime,
        @JsonProperty(value = "completedDateTime") OffsetDateTime completedDateTime) {
        this.scheduledDateTime = scheduledDateTime;
        this.createdDateTime = createdDateTime;
        this.updatedDateTime = updatedDateTime;
        this.completedDateTime = completedDateTime;
    }

    /**
     * Get the scheduledDateTime property: The date and time when the repair is scheduled to occur.
     * 
     * @return the scheduledDateTime value.
     */
    @Generated
    public OffsetDateTime getScheduledDateTime() {
        return this.scheduledDateTime;
    }

    /**
     * Get the createdDateTime property: The date and time when the request was created.
     * 
     * @return the createdDateTime value.
     */
    @Generated
    public OffsetDateTime getCreatedDateTime() {
        return this.createdDateTime;
    }

    /**
     * Get the updatedDateTime property: The date and time when the request was updated.
     * 
     * @return the updatedDateTime value.
     */
    @Generated
    public OffsetDateTime getUpdatedDateTime() {
        return this.updatedDateTime;
    }

    /**
     * Get the completedDateTime property: The date and time when the request was completed.
     * 
     * @return the completedDateTime value.
     */
    @Generated
    public OffsetDateTime getCompletedDateTime() {
        return this.completedDateTime;
    }
}
