// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

module azure.clientgenerator.core.methodoverride {
    requires transitive com.azure.core;

    exports azure.clientgenerator.core.methodoverride;
    exports azure.clientgenerator.core.methodoverride.models;

    opens azure.clientgenerator.core.methodoverride.models to com.azure.core;
}
